<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nami</name>
   <tag></tag>
   <elementGuidId>daea64d1-d856-4c35-915e-0f29e581ed23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src=&quot;https://pops-shop-vn.akamaized.net/2023/03/wVoCi4mz-Nami-300x300.jpg&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
