<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>472db2da-c5d7-4b74-be62-6dea131d75ad</testSuiteGuid>
   <testCaseLink>
      <guid>a7d2deea-b7ad-4cc6-bc67-872614b32019</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login successful when user fills all field with registered email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d567f6ba-2674-4db1-b99b-32205c90068c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05a99ab0-ed22-4222-a758-ffa80dfcb922</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58ce1e0c-d3a5-4e93-9338-632d8f5da766</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login successful when user fills all field with registered email1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d008b2b-1da1-477b-981d-a42a77fb7540</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c18e86a3-db56-4de4-8263-8eb3d159965d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66b689d5-2c9a-4f52-9eef-427126394a66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login unsuccessful when user entered password field less than 6 characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19e4f95b-6625-4137-9084-6827547fc042</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9731fe5-06ee-4c52-acf9-43520c3cf9dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75d789a9-bb93-4824-9ab1-d7f0266697cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login unsuccessful when user entered wrong password field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbf7d899-228d-4ef3-8ffd-5ee32ef6e071</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ca04bb1-1167-4f36-9ae6-6284e1999f08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4b91582-5f47-4cbe-a168-e559aee734aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login unsuccessful when user leaves the email field blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cd7b84c-1443-47e1-aab2-4ff6eba39e5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d69899b2-7778-45c3-92d4-948988171196</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea75f269-239d-429b-a2f6-37250e0f6420</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify login unsuccessful when user leaves the password field blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>697f4fb7-7d8b-4502-81c7-a1c84a730ae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ad78c01-d0bf-4a61-bc0f-d90e58c03b0d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ea21cb3-f121-421c-9e3b-c7357d478a58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify that an error message is displayed when the user enters leading and trailing spaces</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a34a2b44-1de3-48eb-bb04-19de025eb10a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae3989b-edf5-41d4-85d3-891c87ead699</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff5d3867-8f5b-44b7-9e40-27bbeec9521b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify that an error message is displayed when the user enters the wrong password field more than 5 times</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73c5fa07-b6b7-49ed-9094-158648a5f1ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9c43dbe-8f89-47ec-ba9f-115fa30814a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0052bad-386b-4ef8-a63e-b875032c640f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4f7842-d8ee-4c7a-b81a-526c38a34f98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>907b89f7-53d9-4919-ad63-7bb8cfd9df27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c916f153-8aa0-41a5-9ae2-a7cdba9b66cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57999bc5-253e-4d2f-9433-7cc3b4822cb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baea0194-b267-424a-8a89-2fb23f23192f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify that the error message is show when user entered only spaces in the password field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>90a5c3fc-351a-4baa-bada-e65e149baf83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/verify that user is able open successfully the login screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
